<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function products(){
        return $this->hasMany(Product::class);
    }


    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleted(function($category){
        $category->products()->delete();


        });
    }
}
